# Generated by Django 4.1.4 on 2022-12-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_company_company_id_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='Shipping_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
