# Generated by Django 4.1.4 on 2022-12-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_shipping_shipping_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='Pack',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.company'),
            preserve_default=False,
        ),
    ]
