# Generated by Django 4.1.4 on 2022-12-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Addres_contery', models.CharField(max_length=20)),
                ('Addres_street', models.CharField(max_length=20)),
                ('Addres_city', models.CharField(max_length=20)),
                ('Addres_postalCode', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Company_name', models.CharField(max_length=20)),
                ('Company_Email', models.EmailField(max_length=254)),
                ('Company_phone', models.DecimalField(decimal_places=0, max_digits=15)),
                ('Company_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Customer_Email', models.EmailField(max_length=254)),
                ('Customer_phone', models.DecimalField(decimal_places=0, max_digits=15)),
                ('Customer_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('Shipping_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Shipping_name', models.CharField(max_length=20)),
                ('Shipping_price', models.DecimalField(decimal_places=5, max_digits=6)),
                ('Shipping_wight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Shipping_hight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Shipping_Breakable', models.BooleanField(default=None)),
                ('Shipping_address', models.TextField()),
                ('Shipping_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('Tracking_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Tracking_phone', models.DecimalField(decimal_places=0, max_digits=15)),
                ('Tracking_address', models.TextField()),
                ('Tracking_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Vehicle_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Vehicle_model', models.DecimalField(decimal_places=0, max_digits=4)),
                ('Vehicle_color', models.CharField(max_length=10)),
            ],
        ),
    ]
