# Generated by Django 4.1.4 on 2022-12-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='Shipping_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
