# Generated by Django 4.1.4 on 2022-12-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_shipping_shipping_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Company_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='Tracking_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
